# tasks file for this role, can include smaller files if warranted

- name: Update cache
  become: true
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: "{{ cache_valid_time }}"

- name: Upgrade all packages
  become: true
  apt:
    upgrade: dist

- include: reboot.yml
  tags:
    - reboot
