- include_tasks: apt.yml
  tags:
    - apt

- include_tasks: hstr.yml
  tags:
    - hstr
    - apt

- include_tasks: terraform.yml
  tags:
    - terraform
    - apt

- include_tasks: terragrunt.yml
  tags:
    - terragrunt

- include_tasks: packer.yml
  tags:
    - packer

- include_tasks: terraform-docs.yml
  tags:
    - terraform-docs

- include_tasks: tflint.yml
  tags:
    - tflint

- include_tasks: vagrant.yml
  tags:
    - vagrant

- include_tasks: poetry.yml
  tags:
    - poetry

- include_tasks: pipx.yml
  tags:
    - pipx

- include_tasks: pyenv.yml
  tags:
    - pyenv

- include_tasks: pre_commit.yml
  tags:
    - pre-commit

- include_tasks: shell_mods.yml
  tags:
    - shell
    - pipx
    - ssh
