- include: apt.yml
  tags:
    - apt
    - base

- include: hstr.yml
  tags:
    - apt
    - base
    - hstr

- include: packer.yml
  tags:
    - packer

- include: terraform.yml
  tags:
    - apt
    - terraform

- include: terragrunt.yml
  tags:
    - terraform
    - terragrunt

- include: terraform-docs.yml
  tags:
    - terraform
    - terraform-docs

- include: tflint.yml
  tags:
    - terraform
    - tflint

- include: pyenv.yml
  tags:
    - pyenv
    - python

- include: pipx.yml
  tags:
    - pipx
    - python

- include: poetry.yml
  tags:
    - poetry
    - python

- name: Install/update pre-commit
  become: yes
  changed_when: "'Collecting pre-commit' in install.stdout"
  register: install
  shell:
    python3 -m pip install -U pre-commit
  tags:
    - pre-commit
    - base

- include: shell_mods.yml
  tags:
    - shell

- include: vagrant.yml
  tags:
    - vagrant
    - vm

- include: ssh.yml
  tags:
    - ssh
