- name: Check pipx version
  changed_when: "version.rc != 0"
  failed_when: False
  register: version
  command: pipx --version

- name: Install pipx
  when: version is changed
  shell: "{{ ansible_env.HOME }}/.pyenv/shims/python -m pip install --user pipx"

- name: Update pipx
  changed_when: "'Collecting pipx' in update.stdout"
  shell:  "{{ ansible_env.HOME }}/.pyenv/shims/python -m pip install --user -U pipx"
