- name: Check pipx version
  changed_when: "version.rc != 0"
  failed_when: False
  register: version
  command: pipx --version


- name: Install pipx
  when: version is changed
  shell:
    python3 -m pip install --user pipx

- name: Update pipx
  changed_when: "'Collecting pipx' in update.stdout"
  shell:
    python3 -m pip install --user -U pipx
