- name: Check poetry version
  changed_when: "version.rc != 0"
  failed_when: False
  register: version
  command: poetry -V

- name: Install poetry
  when: version is changed
  shell:
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | .pyenv/shims/python

- name: Enable tab completion for Bash
  when: version is changed
  shell:
    $HOME/.poetry/bin/poetry completions bash >> ~/.bash_completion

- name: Update poetry
  changed_when: "'You are using the latest version' not in update.stdout"
  register: update
  shell:
    $HOME/.poetry/bin/poetry self update
