- name: Check pyenv version
  changed_when: "version.rc != 0"
  failed_when: False
  register: version
  command: pyenv --version

- name: Clone pyenv
  when: version is changed
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv"

- name: Install default python for user
  args:
    executable: /bin/bash
  when: version is changed
  shell: >
    PYENV_ROOT="$HOME/.pyenv" &&
    PATH="$PYENV_ROOT/bin:$PATH" &&
    eval "$(pyenv init -)" &&
    pyenv install 3.7.9 &&
    pyenv global 3.7.9
