- name: Check pyenv version
  changed_when: "version.rc != 0"
  failed_when: False
  register: version
  command: pyenv --version

- name: Install pyenv
  when: version is changed
  shell:
    git clone https://github.com/pyenv/pyenv.git ~/.pyenv



- name: Update pyenv
  register: update
  shell:
    cd ~/.pyenv && git pull
  changed_when: "'Already up to date.' not in update.stdout"
  tags:
    - pyenv
