- name: Check pyenv version
  changed_when: "version.rc != 0"
  failed_when: False
  register: version
  command: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv --version"

- name: Clone pyenv
  when: version is changed
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv"

- name: Add pyenv to path
  args:
    executable: /bin/bash
  when: version is changed
  shell: >
    PYENV_ROOT="$HOME/.pyenv" &&
    PATH="$PYENV_ROOT/bin:$PATH" &&
    eval "$(pyenv init -)" 

- name: Get latest python version
  when: version is changed
  register: py_version
  shell: pyenv install --list | grep "3.7" | grep -v - | grep -v b | tail -1

- name: Install default python for user
  args:
    executable: /bin/bash
  when: version is changed
  shell: >
    pyenv install {{ py_version.stdout | trim }} &&
    pyenv global {{ py_version.stdout | trim }}
