- name: Creates ~/.ssh dir
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    recurse: yes
    mode: 0755
  tags:
    - base

- name: Creates ~/.ssh/config
  file:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    state: touch
  tags:
    - base

- name: Create base SSH config file
  blockinfile:
    marker: "# {mark} global config ANSIBLE MANAGED BLOCK"
    block: |
      Host *
        IdentitiesOnly yes
        ControlMaster auto
        ControlPath /tmp/%r@%h-%p
        ServerAliveInterval 30
        ServerAliveCountMax 3
        AddressFamily inet
    path: "{{ ansible_env.HOME }}/.ssh/config"
  tags:
    - base

- name: Copy GitHub SSH key
  copy:
    dest: "{{ ansible_env.HOME }}/.ssh/github_rsa"
    src: /vagrant/github_rsa
    mode: "600"
  tags:
    - github

- name: Add GitHub to SSH config file
  blockinfile:
    marker: "# {mark} GitHub config ANSIBLE MANAGED BLOCK"
    block: |
      Host github.com
        IdentityFile {{ ansible_env.HOME }}/.ssh/github_rsa
        User git
    path: "{{ ansible_env.HOME }}/.ssh/config"
  tags:
    - github
